import type { ThemeRecord } from "./types";

function nowIso(): string {
  return new Date().toISOString();
}

function bundled(input: {
  id: string;
  name: string;
  description: string;
  tokens: ThemeRecord["tokens"];
}): ThemeRecord {
  const stamp = nowIso();
  return {
    id: input.id,
    name: input.name,
    description: input.description,
    source: "bundled",
    createdAt: stamp,
    updatedAt: stamp,
    tokens: input.tokens,
  };
}

export const BUNDLED_THEMES: ThemeRecord[] = [
  bundled({
    id: "theme-midnight-neon",
    name: "Midnight Neon",
    description: "Dark premium contrast with neon accents.",
    tokens: {
      baseColor: "#0b1220",
      accentColor: "#5cf4b7",
      altColor: "#4a7eff",
      linkColor: "#7cd8ff",
      canvasBackground: "#090f1b",
      surfaceBackground: "#111a2b",
      mutedBackground: "#0f1726",
      textPrimary: "#eaf0ff",
      textSecondary: "#b5c1de",
      headingColor: "#f2f6ff",
      buttonBackground: "#5cf4b7",
      buttonText: "#0b1a17",
      buttonAltBackground: "#192a44",
      buttonAltText: "#eaf0ff",
      cardBackground: "#121d30",
      cardBorder: "#2f4268",
    },
  }),
  bundled({
    id: "theme-arctic-minimal",
    name: "Arctic Minimal",
    description: "Clean light surfaces and cool blue accents.",
    tokens: {
      baseColor: "#f5f8ff",
      accentColor: "#2f6cf5",
      altColor: "#1f9ad8",
      linkColor: "#2a63d9",
      canvasBackground: "#f7f9ff",
      surfaceBackground: "#ffffff",
      mutedBackground: "#eef3ff",
      textPrimary: "#121b2d",
      textSecondary: "#4b5a76",
      headingColor: "#0f1a2f",
      buttonBackground: "#2f6cf5",
      buttonText: "#ffffff",
      buttonAltBackground: "#dfe8ff",
      buttonAltText: "#1a2f58",
      cardBackground: "#ffffff",
      cardBorder: "#d9e4fb",
    },
  }),
  bundled({
    id: "theme-sandstone-editorial",
    name: "Sandstone Editorial",
    description: "Warm neutral palette for content-heavy sites.",
    tokens: {
      baseColor: "#f4efe7",
      accentColor: "#a45728",
      altColor: "#5e6a83",
      linkColor: "#8f3e18",
      canvasBackground: "#f2ece2",
      surfaceBackground: "#fffaf2",
      mutedBackground: "#ece1d0",
      textPrimary: "#2a251f",
      textSecondary: "#5e5448",
      headingColor: "#1f1a15",
      buttonBackground: "#a45728",
      buttonText: "#fff7ee",
      buttonAltBackground: "#e9dcc8",
      buttonAltText: "#4f3624",
      cardBackground: "#fffaf2",
      cardBorder: "#d9c7ab",
    },
  }),
  bundled({
    id: "theme-emerald-modern",
    name: "Emerald Modern",
    description: "High trust green-forward business palette.",
    tokens: {
      baseColor: "#0f251e",
      accentColor: "#23d18b",
      altColor: "#1ea36f",
      linkColor: "#38ddb3",
      canvasBackground: "#0e201b",
      surfaceBackground: "#152d26",
      mutedBackground: "#102720",
      textPrimary: "#e7fff5",
      textSecondary: "#a5d0bf",
      headingColor: "#f0fff8",
      buttonBackground: "#23d18b",
      buttonText: "#0d241c",
      buttonAltBackground: "#1a4034",
      buttonAltText: "#d8ffef",
      cardBackground: "#17362d",
      cardBorder: "#2f735f",
    },
  }),
  bundled({
    id: "theme-violet-luxe",
    name: "Violet Luxe",
    description: "Luxury dark palette with vivid art-direction accents.",
    tokens: {
      baseColor: "#171026",
      accentColor: "#d26bff",
      altColor: "#7a5cff",
      linkColor: "#b996ff",
      canvasBackground: "#120b1f",
      surfaceBackground: "#1d1430",
      mutedBackground: "#170f27",
      textPrimary: "#f4ecff",
      textSecondary: "#c9b8e8",
      headingColor: "#fff6ff",
      buttonBackground: "#d26bff",
      buttonText: "#2c1140",
      buttonAltBackground: "#31204f",
      buttonAltText: "#f1e8ff",
      cardBackground: "#24183a",
      cardBorder: "#4f3a77",
    },
  }),
  bundled({
    id: "theme-slate-mono",
    name: "Slate Mono",
    description: "Monochrome neutral baseline for product-led sites.",
    tokens: {
      baseColor: "#0f1216",
      accentColor: "#d7dde9",
      altColor: "#7f8a9f",
      linkColor: "#c1cfeb",
      canvasBackground: "#0d1117",
      surfaceBackground: "#141a22",
      mutedBackground: "#111722",
      textPrimary: "#e9edf5",
      textSecondary: "#a4afc3",
      headingColor: "#f3f7ff",
      buttonBackground: "#e7edf8",
      buttonText: "#111823",
      buttonAltBackground: "#232c3b",
      buttonAltText: "#e6edf8",
      cardBackground: "#171f2a",
      cardBorder: "#2a3446",
    },
  }),
];
