import type { BundledThemeDefinition } from "../library";

const theme: BundledThemeDefinition = {
  id: "theme-arctic-minimal",
  name: "Arctic Minimal",
  description: "Bright editorial minimalism with precise cobalt accents.",
  order: 20,
  tokens: {
    baseColor: "#f4f8ff",
    accentColor: "#2f5cff",
    altColor: "#21a5d8",
    linkColor: "#2d55d8",
    canvasBackground: "#f6f9ff",
    surfaceBackground: "#ffffff",
    mutedBackground: "#edf3ff",
    textPrimary: "#111b2f",
    textSecondary: "#4a5c7e",
    headingColor: "#0e172c",
    buttonBackground: "#2f5cff",
    buttonText: "#ffffff",
    buttonAltBackground: "#dee7ff",
    buttonAltText: "#1c2f63",
    buttonRadius: "999px",
    buttonPaddingX: "19px",
    buttonPaddingY: "10px",
    buttonPrimaryBorderColor: "#2f5cff",
    buttonPrimaryBorderWidth: "1px",
    buttonPrimaryBorderStyle: "solid",
    buttonPrimaryShadow: "0 10px 22px rgba(47, 92, 255, 0.23)",
    buttonSecondaryBorderColor: "#b9ccfb",
    buttonSecondaryBorderWidth: "1px",
    buttonSecondaryBorderStyle: "solid",
    buttonSecondaryShadow: "none",
    buttonGhostBackground: "transparent",
    buttonGhostText: "#2148be",
    buttonGhostBorderColor: "#99b3f1",
    buttonGhostBorderWidth: "1px",
    buttonGhostBorderStyle: "solid",
    buttonGhostShadow: "none",
    cardBackground: "#ffffff",
    cardBorder: "#d8e4fb",
    cardBorderWidth: "1px",
    cardBorderStyle: "solid",
    cardRadius: "14px",
    cardShadow: "0 10px 24px rgba(38, 74, 156, 0.09)",
    fontFamilyBody: '"Inter", "Manrope", "Segoe UI", sans-serif',
    fontFamilyHeading: '"Plus Jakarta Sans", "Inter", "Segoe UI", sans-serif',
    fontWeightBody: "420",
    fontWeightHeading: "700",
    fontSizeBody: "18px",
    lineHeightBody: "1.62",
    fontSizeH1: "62px",
    fontSizeH2: "42px",
    fontSizeH3: "24px",
    lineHeightHeading: "1.08",
    letterSpacingHeading: "-0.022em",
  },
};

export default theme;
