import type { BundledThemeDefinition } from "../library";

const theme: BundledThemeDefinition = {
  id: "theme-emerald-modern",
  name: "Emerald Modern",
  description: "Earthy pastel green palette with bold modern-sans headlines and serif body copy.",
  order: 40,
  tokens: {
    baseColor: "#7c8f76",
    accentColor: "#c8b89a",
    altColor: "#a8b59a",
    linkColor: "#6a7b5f",
    canvasBackground: "#f1ede4",
    surfaceBackground: "#f7f3ea",
    mutedBackground: "#e5e0d3",
    textPrimary: "#3a4335",
    textSecondary: "#68715f",
    headingColor: "#2d3729",
    buttonBackground: "#8ea180",
    buttonText: "#f8f4ea",
    buttonAltBackground: "#ded8c9",
    buttonAltText: "#4a5441",
    buttonRadius: "12px",
    buttonPaddingX: "18px",
    buttonPaddingY: "11px",
    buttonPrimaryBorderColor: "#7f9271",
    buttonPrimaryBorderWidth: "1px",
    buttonPrimaryBorderStyle: "solid",
    buttonPrimaryShadow: "0 10px 22px rgba(76, 93, 64, 0.2)",
    buttonSecondaryBorderColor: "#c8bfae",
    buttonSecondaryBorderWidth: "1px",
    buttonSecondaryBorderStyle: "solid",
    buttonSecondaryShadow: "none",
    buttonGhostBackground: "transparent",
    buttonGhostText: "#6b7a5f",
    buttonGhostBorderColor: "#a9b59a",
    buttonGhostBorderWidth: "1px",
    buttonGhostBorderStyle: "solid",
    buttonGhostShadow: "none",
    cardBackground: "#f8f5ed",
    cardBorder: "#d2cbbb",
    cardBorderWidth: "1px",
    cardBorderStyle: "solid",
    cardRadius: "16px",
    cardShadow: "0 10px 24px rgba(74, 66, 48, 0.12)",
    fontFamilyBody: '"Source Serif 4", "Georgia", serif',
    fontFamilyHeading: '"Outfit", "Inter", "Segoe UI", sans-serif',
    fontWeightBody: "400",
    fontWeightHeading: "760",
    fontSizeBody: "19px",
    lineHeightBody: "1.62",
    fontSizeH1: "63px",
    fontSizeH2: "43px",
    fontSizeH3: "24px",
    lineHeightHeading: "1.06",
    letterSpacingHeading: "-0.022em",
  },
};

export default theme;
