import type { BundledThemeDefinition } from "../library";

const theme: BundledThemeDefinition = {
  id: "theme-midnight-neon",
  name: "Midnight Neon",
  description: "Cinematic dark mode with electric mint and cobalt contrast.",
  order: 10,
  tokens: {
    baseColor: "#0a1220",
    accentColor: "#52f6c2",
    altColor: "#5f7dff",
    linkColor: "#8de3ff",
    canvasBackground: "#070d19",
    surfaceBackground: "#0f1a2e",
    mutedBackground: "#0c1628",
    textPrimary: "#eaf3ff",
    textSecondary: "#a9bddf",
    headingColor: "#f5f9ff",
    buttonBackground: "#52f6c2",
    buttonText: "#081b18",
    buttonAltBackground: "#182b48",
    buttonAltText: "#e8f1ff",
    buttonRadius: "14px",
    buttonPaddingX: "20px",
    buttonPaddingY: "12px",
    buttonPrimaryBorderColor: "#89ffda",
    buttonPrimaryBorderWidth: "1px",
    buttonPrimaryBorderStyle: "solid",
    buttonPrimaryShadow: "0 14px 32px rgba(82, 246, 194, 0.3)",
    buttonSecondaryBorderColor: "#6f8dff",
    buttonSecondaryBorderWidth: "1px",
    buttonSecondaryBorderStyle: "solid",
    buttonSecondaryShadow: "0 10px 24px rgba(95, 125, 255, 0.24)",
    buttonGhostBackground: "rgba(141, 227, 255, 0.08)",
    buttonGhostText: "#ccefff",
    buttonGhostBorderColor: "rgba(141, 227, 255, 0.58)",
    buttonGhostBorderWidth: "1px",
    buttonGhostBorderStyle: "solid",
    buttonGhostShadow: "none",
    cardBackground: "#111f35",
    cardBorder: "#2a456f",
    cardBorderWidth: "1px",
    cardBorderStyle: "solid",
    cardRadius: "18px",
    cardShadow: "0 18px 40px rgba(6, 13, 26, 0.54)",
    fontFamilyBody: '"DM Sans", "Inter", "Segoe UI", sans-serif',
    fontFamilyHeading: '"Space Grotesk", "Inter", "Segoe UI", sans-serif',
    fontWeightBody: "430",
    fontWeightHeading: "720",
    fontSizeBody: "19px",
    lineHeightBody: "1.6",
    fontSizeH1: "64px",
    fontSizeH2: "44px",
    fontSizeH3: "25px",
    lineHeightHeading: "1.05",
    letterSpacingHeading: "-0.026em",
  },
};

export default theme;
