import type { BundledThemeDefinition } from "../library";

const theme: BundledThemeDefinition = {
  id: "theme-midnight-neon",
  name: "Midnight Neon",
  description: "Dark premium contrast with neon accents.",
  order: 10,
  tokens: {
    baseColor: "#0b1220",
    accentColor: "#5cf4b7",
    altColor: "#4a7eff",
    linkColor: "#7cd8ff",
    canvasBackground: "#090f1b",
    surfaceBackground: "#111a2b",
    mutedBackground: "#0f1726",
    textPrimary: "#eaf0ff",
    textSecondary: "#b5c1de",
    headingColor: "#f2f6ff",
    buttonBackground: "#5cf4b7",
    buttonText: "#0b1a17",
    buttonAltBackground: "#192a44",
    buttonAltText: "#eaf0ff",
    buttonRadius: "14px",
    buttonPaddingX: "20px",
    buttonPaddingY: "12px",
    buttonPrimaryBorderColor: "#7cffcc",
    buttonPrimaryBorderWidth: "1px",
    buttonPrimaryBorderStyle: "solid",
    buttonPrimaryShadow: "0 10px 24px rgba(92, 244, 183, 0.32)",
    buttonSecondaryBorderColor: "#4a7eff",
    buttonSecondaryBorderWidth: "1px",
    buttonSecondaryBorderStyle: "solid",
    buttonSecondaryShadow: "0 8px 20px rgba(74, 126, 255, 0.22)",
    buttonGhostBackground: "rgba(124, 216, 255, 0.08)",
    buttonGhostText: "#c6ebff",
    buttonGhostBorderColor: "rgba(124, 216, 255, 0.58)",
    buttonGhostBorderWidth: "1px",
    buttonGhostBorderStyle: "solid",
    buttonGhostShadow: "none",
    cardBackground: "#121d30",
    cardBorder: "#2f4268",
    cardBorderWidth: "1px",
    cardBorderStyle: "solid",
    cardRadius: "16px",
    cardShadow: "0 14px 32px rgba(10, 16, 31, 0.5)",
    fontFamilyBody: '"Inter", "Manrope", "Segoe UI", sans-serif',
    fontFamilyHeading: '"Space Grotesk", "Inter", "Segoe UI", sans-serif',
    fontWeightBody: "400",
    fontWeightHeading: "700",
    fontSizeBody: "19px",
    lineHeightBody: "1.6",
    fontSizeH1: "62px",
    fontSizeH2: "42px",
    fontSizeH3: "24px",
    lineHeightHeading: "1.06",
    letterSpacingHeading: "-0.025em",
  },
};

export default theme;
