import type { BundledThemeDefinition } from "../library";

const theme: BundledThemeDefinition = {
  id: "theme-sandstone-editorial",
  name: "Sandstone Editorial",
  description: "Warm premium serif system for narrative and brand-rich layouts.",
  order: 30,
  tokens: {
    baseColor: "#f3ece2",
    accentColor: "#a7582a",
    altColor: "#5d687f",
    linkColor: "#8e401b",
    canvasBackground: "#efe7db",
    surfaceBackground: "#fff9f0",
    mutedBackground: "#e8dbc8",
    textPrimary: "#2a241e",
    textSecondary: "#605548",
    headingColor: "#1f1914",
    buttonBackground: "#a7582a",
    buttonText: "#fff8ef",
    buttonAltBackground: "#eadcc7",
    buttonAltText: "#4e3523",
    buttonRadius: "8px",
    buttonPaddingX: "17px",
    buttonPaddingY: "10px",
    buttonPrimaryBorderColor: "#b96a3a",
    buttonPrimaryBorderWidth: "1px",
    buttonPrimaryBorderStyle: "solid",
    buttonPrimaryShadow: "0 8px 18px rgba(116, 67, 35, 0.22)",
    buttonSecondaryBorderColor: "#c8b396",
    buttonSecondaryBorderWidth: "1px",
    buttonSecondaryBorderStyle: "solid",
    buttonSecondaryShadow: "none",
    buttonGhostBackground: "transparent",
    buttonGhostText: "#7d4320",
    buttonGhostBorderColor: "#c3a98b",
    buttonGhostBorderWidth: "1px",
    buttonGhostBorderStyle: "solid",
    buttonGhostShadow: "none",
    cardBackground: "#fff9f0",
    cardBorder: "#d8c5aa",
    cardBorderWidth: "1px",
    cardBorderStyle: "solid",
    cardRadius: "8px",
    cardShadow: "0 8px 18px rgba(80, 57, 37, 0.11)",
    fontFamilyBody: '"Source Serif 4", "Georgia", serif',
    fontFamilyHeading: '"DM Serif Display", "Source Serif 4", "Georgia", serif',
    fontWeightBody: "400",
    fontWeightHeading: "560",
    fontSizeBody: "20px",
    lineHeightBody: "1.72",
    fontSizeH1: "68px",
    fontSizeH2: "47px",
    fontSizeH3: "26px",
    lineHeightHeading: "1.1",
    letterSpacingHeading: "-0.014em",
  },
};

export default theme;
