import type { BundledThemeDefinition } from "../library";

const theme: BundledThemeDefinition = {
  id: "theme-slate-mono",
  name: "Slate Mono",
  description: "Monochrome neutral baseline for product-led sites.",
  order: 60,
  tokens: {
    baseColor: "#0f1216",
    accentColor: "#d7dde9",
    altColor: "#7f8a9f",
    linkColor: "#c1cfeb",
    canvasBackground: "#0d1117",
    surfaceBackground: "#141a22",
    mutedBackground: "#111722",
    textPrimary: "#e9edf5",
    textSecondary: "#a4afc3",
    headingColor: "#f3f7ff",
    buttonBackground: "#e7edf8",
    buttonText: "#111823",
    buttonAltBackground: "#232c3b",
    buttonAltText: "#e6edf8",
    buttonRadius: "8px",
    buttonPaddingX: "16px",
    buttonPaddingY: "10px",
    buttonPrimaryBorderColor: "#c3cfdf",
    buttonPrimaryBorderWidth: "1px",
    buttonPrimaryBorderStyle: "solid",
    buttonPrimaryShadow: "0 6px 14px rgba(7, 10, 16, 0.2)",
    buttonSecondaryBorderColor: "#39465f",
    buttonSecondaryBorderWidth: "1px",
    buttonSecondaryBorderStyle: "solid",
    buttonSecondaryShadow: "none",
    buttonGhostBackground: "transparent",
    buttonGhostText: "#d7dfef",
    buttonGhostBorderColor: "#465673",
    buttonGhostBorderWidth: "1px",
    buttonGhostBorderStyle: "solid",
    buttonGhostShadow: "none",
    cardBackground: "#171f2a",
    cardBorder: "#2a3446",
    cardBorderWidth: "1px",
    cardBorderStyle: "solid",
    cardRadius: "10px",
    cardShadow: "0 8px 18px rgba(6, 10, 17, 0.3)",
    fontFamilyBody: '"IBM Plex Sans", "Inter", "Segoe UI", sans-serif',
    fontFamilyHeading: '"IBM Plex Sans", "Inter", "Segoe UI", sans-serif',
    fontWeightBody: "400",
    fontWeightHeading: "650",
    fontSizeBody: "18px",
    lineHeightBody: "1.6",
    fontSizeH1: "58px",
    fontSizeH2: "40px",
    fontSizeH3: "22px",
    lineHeightHeading: "1.1",
    letterSpacingHeading: "-0.018em",
  },
};

export default theme;
