import type { BundledThemeDefinition } from "../library";

const theme: BundledThemeDefinition = {
  id: "theme-slate-mono",
  name: "Slate Mono",
  description: "Graphite and slate premium dark theme with muted contrast and clean readability.",
  order: 60,
  tokens: {
    baseColor: "#2f343c",
    accentColor: "#b8c1cf",
    altColor: "#5f6978",
    linkColor: "#c6d0de",
    canvasBackground: "#23282f",
    surfaceBackground: "#2b3139",
    mutedBackground: "#252b33",
    textPrimary: "#e3e8f0",
    textSecondary: "#a6afbc",
    headingColor: "#f0f4fb",
    buttonBackground: "#d8dee9",
    buttonText: "#262c34",
    buttonAltBackground: "#3a424d",
    buttonAltText: "#e4e9f1",
    buttonRadius: "10px",
    buttonPaddingX: "17px",
    buttonPaddingY: "10px",
    buttonPrimaryBorderColor: "#b8c2d2",
    buttonPrimaryBorderWidth: "1px",
    buttonPrimaryBorderStyle: "solid",
    buttonPrimaryShadow: "0 8px 18px rgba(34, 39, 47, 0.28)",
    buttonSecondaryBorderColor: "#556173",
    buttonSecondaryBorderWidth: "1px",
    buttonSecondaryBorderStyle: "solid",
    buttonSecondaryShadow: "none",
    buttonGhostBackground: "transparent",
    buttonGhostText: "#d0d8e6",
    buttonGhostBorderColor: "#667286",
    buttonGhostBorderWidth: "1px",
    buttonGhostBorderStyle: "solid",
    buttonGhostShadow: "none",
    cardBackground: "#303742",
    cardBorder: "#4a5565",
    cardBorderWidth: "1px",
    cardBorderStyle: "solid",
    cardRadius: "12px",
    cardShadow: "0 10px 24px rgba(28, 33, 40, 0.34)",
    fontFamilyBody: '"IBM Plex Sans", "Inter", "Segoe UI", sans-serif',
    fontFamilyHeading: '"Plus Jakarta Sans", "IBM Plex Sans", "Inter", sans-serif',
    fontWeightBody: "420",
    fontWeightHeading: "670",
    fontSizeBody: "18px",
    lineHeightBody: "1.6",
    fontSizeH1: "58px",
    fontSizeH2: "40px",
    fontSizeH3: "22px",
    lineHeightHeading: "1.08",
    letterSpacingHeading: "-0.018em",
  },
};

export default theme;
