import type { BundledThemeDefinition } from "../library";

const theme: BundledThemeDefinition = {
  id: "theme-violet-luxe",
  name: "Violet Luxe",
  description: "Rich deep-pastel violet palette with luxe editorial contrast.",
  order: 50,
  tokens: {
    baseColor: "#511143",
    accentColor: "#ffdad8",
    altColor: "#f2d9cd",
    linkColor: "#ffd3ea",
    canvasBackground: "#511143",
    surfaceBackground: "#7a4779",
    mutedBackground: "#62315f",
    textPrimary: "#f2d9cd",
    textSecondary: "#efc8d0",
    headingColor: "#ffdad8",
    buttonBackground: "#ffdad8",
    buttonText: "#4b173f",
    buttonAltBackground: "#7a4779",
    buttonAltText: "#ffdad8",
    buttonRadius: "999px",
    buttonPaddingX: "21px",
    buttonPaddingY: "12px",
    buttonPrimaryBorderColor: "#ffd1d8",
    buttonPrimaryBorderWidth: "1px",
    buttonPrimaryBorderStyle: "solid",
    buttonPrimaryShadow: "0 12px 28px rgba(255, 194, 208, 0.24)",
    buttonSecondaryBorderColor: "#c991b5",
    buttonSecondaryBorderWidth: "1px",
    buttonSecondaryBorderStyle: "solid",
    buttonSecondaryShadow: "0 8px 20px rgba(50, 12, 42, 0.24)",
    buttonGhostBackground: "rgba(255, 218, 216, 0.1)",
    buttonGhostText: "#ffdad8",
    buttonGhostBorderColor: "#d8a6be",
    buttonGhostBorderWidth: "1px",
    buttonGhostBorderStyle: "solid",
    buttonGhostShadow: "none",
    cardBackground: "#6c3f6d",
    cardBorder: "#b984aa",
    cardBorderWidth: "1px",
    cardBorderStyle: "solid",
    cardRadius: "20px",
    cardShadow: "0 14px 30px rgba(36, 8, 30, 0.38)",
    fontFamilyBody: '"Manrope", "IBM Plex Sans", "Avenir Next", "Segoe UI", sans-serif',
    fontFamilyHeading: '"Space Grotesk", "Inter", "Segoe UI", sans-serif',
    fontWeightBody: "300",
    fontWeightHeading: "800",
    fontSizeBody: "19px",
    lineHeightBody: "1.62",
    fontSizeH1: "64px",
    fontSizeH2: "44px",
    fontSizeH3: "24px",
    lineHeightHeading: "1.05",
    letterSpacingHeading: "-0.026em",
  },
};

export default theme;
