import type { BundledThemeDefinition } from "../library";

const theme: BundledThemeDefinition = {
  id: "theme-violet-luxe",
  name: "Violet Luxe",
  description: "Luxury dark palette with vivid art-direction accents.",
  order: 50,
  tokens: {
    baseColor: "#171026",
    accentColor: "#d26bff",
    altColor: "#7a5cff",
    linkColor: "#b996ff",
    canvasBackground: "#120b1f",
    surfaceBackground: "#1d1430",
    mutedBackground: "#170f27",
    textPrimary: "#f4ecff",
    textSecondary: "#c9b8e8",
    headingColor: "#fff6ff",
    buttonBackground: "#d26bff",
    buttonText: "#2c1140",
    buttonAltBackground: "#31204f",
    buttonAltText: "#f1e8ff",
    buttonRadius: "999px",
    buttonPaddingX: "20px",
    buttonPaddingY: "12px",
    buttonPrimaryBorderColor: "#d88bff",
    buttonPrimaryBorderWidth: "1px",
    buttonPrimaryBorderStyle: "solid",
    buttonPrimaryShadow: "0 12px 28px rgba(210, 107, 255, 0.34)",
    buttonSecondaryBorderColor: "#6c4fb2",
    buttonSecondaryBorderWidth: "1px",
    buttonSecondaryBorderStyle: "solid",
    buttonSecondaryShadow: "0 8px 20px rgba(122, 92, 255, 0.2)",
    buttonGhostBackground: "rgba(185, 150, 255, 0.08)",
    buttonGhostText: "#e5d2ff",
    buttonGhostBorderColor: "rgba(185, 150, 255, 0.58)",
    buttonGhostBorderWidth: "1px",
    buttonGhostBorderStyle: "solid",
    buttonGhostShadow: "none",
    cardBackground: "#24183a",
    cardBorder: "#4f3a77",
    cardBorderWidth: "1px",
    cardBorderStyle: "solid",
    cardRadius: "18px",
    cardShadow: "0 14px 34px rgba(20, 10, 36, 0.44)",
    fontFamilyBody: '"Inter", "Manrope", "Segoe UI", sans-serif',
    fontFamilyHeading: '"Sora", "Inter", "Segoe UI", sans-serif',
    fontWeightBody: "400",
    fontWeightHeading: "700",
    fontSizeBody: "19px",
    lineHeightBody: "1.62",
    fontSizeH1: "64px",
    fontSizeH2: "44px",
    fontSizeH3: "24px",
    lineHeightHeading: "1.06",
    letterSpacingHeading: "-0.028em",
  },
};

export default theme;
